name: Publish image to GitHub Container Registry

on:
  push:
    branches:
      - main
      - deploy
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: {% raw %}${{ github.actor }}{% endraw %}
          password: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}

      - name: Create tag from branch
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/{% raw %}${{ github.repository }}{% endraw %}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: {% raw %}${{ steps.meta.outputs.tags }}{% endraw %}
