FROM ghcr.io/datamade/{{ cookiecutter.project_slug }}:main

# Install any requirements not in the base image
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./package.json /app/package.json
RUN npm install

COPY . /app

# Rebuild static files
RUN npm run build

ENV DJANGO_SECRET_KEY 'foobar'
RUN python manage.py collectstatic --noinput
