services:
  webpack:
    # Runs the webpack server for local development.
    build:
      context: .
      dockerfile: Dockerfile
      target: node
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - {{ cookiecutter.module_name }}-node-modules:/app/node_modules
    command: npm run serve

  app:
    image: {{ cookiecutter.module_name }}
    container_name: {{ cookiecutter.module_name }}
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - {{ cookiecutter.module_name }}-node-modules:/app/node_modules
    environment:
      DJANGO_SECRET_KEY: reallysupersecret
      DJANGO_MANAGEPY_MIGRATE: "on"
      DJANGO_DEBUG: "True"
      PGPASSWORD: postgres
    env_file:
      - .env
    entrypoint: /app/docker-entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    container_name: {{ cookiecutter.module_name }}-postgres
    image: {% if cookiecutter.install_postgis %}postgis/postgis{% else %}postgres{% endif %}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: {{ cookiecutter.module_name }}
    volumes:
      - {{ cookiecutter.module_name }}-db-data:/var/lib/postgresql/data
    ports:
      - 32001:5432

volumes:
  {{ cookiecutter.module_name }}-db-data:
  {{ cookiecutter.module_name }}-node-modules:
